package client

import (
	"encoding/json"
)

const redacted = "[REDACTED]"

// RedactVariables returns logging-safe structural metadata for GraphQL
// variables. Top-level names are generated by the checked-in operations and
// remain useful diagnostics. Nested object keys and every scalar are removed:
// either can be practitioner-controlled data, regardless of what the key is
// called.
func RedactVariables(value any) any {
	variables, ok := value.(map[string]any)
	if !ok {
		return redactShape(value)
	}

	result := make(map[string]any, len(variables))
	for key, child := range variables {
		result[key] = redactShape(child)
	}
	return result
}

func redactShape(value any) any {
	switch typed := value.(type) {
	case map[string]any:
		children := make([]any, 0, len(typed))
		for _, child := range typed {
			children = append(children, redactShape(child))
		}
		return map[string]any{
			"railway_redacted_type":     "object",
			"railway_redacted_fields":   len(typed),
			"railway_redacted_children": children,
		}
	case []any:
		children := make([]any, len(typed))
		for index, child := range typed {
			children[index] = redactShape(child)
		}
		return map[string]any{
			"railway_redacted_type":     "array",
			"railway_redacted_items":    len(typed),
			"railway_redacted_children": children,
		}
	case json.RawMessage:
		var decoded any
		if json.Unmarshal(typed, &decoded) == nil {
			return redactShape(decoded)
		}
		return redacted
	case nil:
		return nil
	default:
		return redacted
	}
}
